set etcdBackupPassphrase in chart
giantswarm/etcd-backup-operator pull request #371
Opened 2023-02-13 12:37 UTC by kamal-pandala-thg

PR to allow `ETCDBACKUP_PASSPHRASE` value in secret template to be set from the value `etcdBackupPassphrase`. This should allow for enabling encryption of the backup via the provided passphrase.

2023-02-13 12:46 UTC, whites11 requested changes
Thanks for the contribution @kamal-pandala-thg 
Can you please add a changelog entry in CHANGELOG.md for the change as well?

2023-02-13 12:55 UTC, thg-adamdean approved these changes

2023-02-13 12:56 UTC, kamal-pandala-thg commented
> Thanks for the contribution @kamal-pandala-thg Can you please add a changelog entry in CHANGELOG.md for the change as well?

Added the entry under 'Unreleased' section, thanks!

2023-02-13 13:36 UTC, whites11 commented
Looking more closely, I think there is another problem as well.
The env variable that gets populated from the secret that you fixed is called `ETCDBACKUP_PASSPHRASE` (see https://github.com/giantswarm/etcd-backup-operator/blob/master/helm/etcd-backup-operator/templates/deployment.yaml#L94) but in the code we use a different name `ENCRYPTION_PASSWORD` (see https://github.com/giantswarm/etcd-backup-operator/blob/master/service/controller/key/key.go#L26)

I think `ENCRYPTION_PASSWORD` is clearer at indicating the env's meaning.
Do you mind renaming the [deployment template](https://github.com/giantswarm/etcd-backup-operator/blob/master/helm/etcd-backup-operator/templates/deployment.yaml) as well?

Thanks!

2023-02-13 14:22 UTC, kamal-pandala-thg commented
> Looking more closely, I think there is another problem as well. The env variable that gets populated from the secret that you fixed is called `ETCDBACKUP_PASSPHRASE` (see https://github.com/giantswarm/etcd-backup-operator/blob/master/helm/etcd-backup-operator/templates/deployment.yaml#L94) but in the code we use a different name `ENCRYPTION_PASSWORD` (see https://github.com/giantswarm/etcd-backup-operator/blob/master/service/controller/key/key.go#L26)
> 
> I think `ENCRYPTION_PASSWORD` is clearer at indicating the env's meaning. Do you mind renaming the [deployment template](https://github.com/giantswarm/etcd-backup-operator/blob/master/helm/etcd-backup-operator/templates/deployment.yaml) as well?
> 
> Thanks!

Good spot! I have updated the chart to use `ENCRYPTION_PASSWORD` as the env variable and `ETCDBACKUP_ENCRYPTION_PASSWORD` as the chart variable.

2023-02-13 14:27 UTC, whites11 approved these changes
Looks good to me!

2023-02-17 09:35 UTC, kamal-pandala-thg commented
Thanks @whites11! Could I get an approver from a maintainer to trigger the workflows, please? And also, when can this be made available as a new version, please?

2023-02-19 10:09 UTC, whites11 commented
> @whites11, seems like the "values and schema" workflow fails when the changes are made on a branch in a forked repo. How would you like for me to proceed, please?

Will take care asap

2023-02-20 10:05 UTC, eugene-eeo commented
@whites11 I've run that command now, let me know if you need anything else.

2023-02-20 10:23 UTC, whites11 commented
Unfortunately there is a bug in our automation, let me check what I can do

2023-02-20 10:24 UTC, merged

2023-02-20 11:32 UTC, whites11 commented
this was released in version 4.3.0. Thanks for your contribution @eugene-eeo @kamal-pandala-thg