Use pod monitor
giantswarm/etcd-backup-operator pull request #562
Opened 2024-03-30 14:40 UTC by QuentinBisson

This configures the operator to be scraped using a pod monitor instead of the old scheme

2024-03-30 17:40 UTC, weseven approved these changes

2024-04-01 09:53 UTC, Gacko commented
Your PR says it makes use of a PodMonitor while you're actually using a ServiceMonitor? IMHO we can drop the service and really just use a PodMonitor as you proposed for the `etcd-kubernetes-resources-count-exporter`.

2024-04-01 09:54 UTC, Gacko requested changes
Your PR says it makes use of a PodMonitor while you're actually using a ServiceMonitor? IMHO we can drop the service and really just use a PodMonitor as you proposed for the `etcd-kubernetes-resources-count-exporter`.

2024-04-01 09:55 UTC, QuentinBisson commented
I tried but it does not work because this pod is using hostnetwork:true

2024-04-01 09:58 UTC, Gacko commented
But that's probably more an issue because of not using CiliumNetworkPolicies, right? Like, plain NetworkPolicies can not be used for allowing traffic to host network.

2024-04-01 10:00 UTC, QuentinBisson commented
Hmm thé issue I had was really related to kyverno policy exceptions but you're free to try a Pod monitor instead :) I don't have the bandwith to do them all "properly", I really just need to get rid of the old annotations asap:)

2024-04-01 10:37 UTC, Gacko approved these changes

2024-04-01 10:37 UTC, Gacko commented on helm/etcd-backup-operator/templates/service.yaml
> +    {{- include "labels.selector" . | nindent 4 }}
```suggestion
    {{- include "labels.selector" . | nindent 4 }}
```

Adding the missing/removed newline at EOF.

2024-04-01 10:39 UTC, Gacko requested changes
Ah, one more: Then please do not change the values (replace `service.port` by just `port`) if you keep using a ServiceMonitor.

2024-04-01 10:40 UTC, QuentinBisson commented
Sure :)

2024-04-01 12:03 UTC, QuentinBisson commented
It's fixed @Gacko

2024-04-01 14:18 UTC, Gacko approved these changes

2024-04-01 14:19 UTC, merged